# Site settings
title: VizLab
email: Jayson.xu@foxmail.com
description: ""
baseurl: "/blog"
url: "http://akadealloc.github.io"
twitter_username: ecs_tee
github_username:  akadealloc

# Build settings
markdown: kramdown
