# Site settings
name: VizLab
email: Jayson.xu@foxmail.com
description: ""
intro: What's down there
url: "http://akadealloc.github.io/blog"
twitter_username: ecs_tee
github_username:  akadealloc
logo:             logo.png

# Build settings
paginate: 8
markdown: redcarpet
permalink:    pretty
